#!/usr/bin/env python3
"""Generate the National Dex 1-649 roster from PokéAPI bulk CSVs.

Dev tool, run manually (network):
    python3 tools/gen_dex.py

Gen 1-5 spans #1-649; the pokecrystal disassembly only reaches Gen 2, so types,
catch rates, and legendary/mythical flags come from PokéAPI's CSV data dump.
Writes lib/dex_roster.py (committed literal so the runtime stays offline).
Rarity = legendary/mythical flag, else catch-rate bands.
"""
import csv
import io
import sys
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

POKEAPI_CSV = "https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv"
MAX_DEX = 649

STARTER_LINES = {
    "Bulbasaur", "Ivysaur", "Venusaur", "Charmander", "Charmeleon", "Charizard",
    "Squirtle", "Wartortle", "Blastoise", "Pikachu", "Raichu", "Eevee",
    "Vaporeon", "Jolteon", "Flareon",
}

TYPE_EMOJI = {
    "Normal": "🐾", "Fire": "🔥", "Water": "💧", "Electric": "⚡", "Grass": "🌿",
    "Ice": "❄️", "Fighting": "🥊", "Poison": "☠️", "Ground": "⛰️", "Flying": "🕊️",
    "Psychic": "🔮", "Bug": "🐛", "Rock": "🪨", "Ghost": "👻", "Dragon": "🐉",
    "Dark": "🌑", "Steel": "⚙️", "Fairy": "🧚",
}

# Display names whose title-cased identifier needs a fix.
SPECIAL_NAME = {
    "nidoran-f": "Nidoran♀", "nidoran-m": "Nidoran♂", "mr-mime": "Mr. Mime",
    "farfetchd": "Farfetch'd", "ho-oh": "Ho-Oh", "mime-jr": "Mime Jr.",
    "porygon-z": "Porygon-Z", "type-null": "Type: Null",  # (>649, harmless)
}

CURATED_EMOJI = {
    'Pidgey': '🐦', 'Rattata': '🐀', 'Caterpie': '🐛', 'Weedle': '🐝',
    'Zubat': '🦇', 'Oddish': '🌿', 'Poliwag': '🌀', 'Magikarp': '🐟',
    'Sentret': '🐿️', 'Hoothoot': '🦉', 'Sandshrew': '🦔', 'Vulpix': '🦊',
    'Growlithe': '🐕', 'Abra': '🥄', 'Machop': '💪', 'Geodude': '🪨',
    'Gastly': '👻', 'Cubone': '🦴', 'Togepi': '🥚', 'Mareep': '🐏',
    'Snorlax': '😴', 'Lapras': '🦕', 'Aerodactyl': '🦖', 'Dratini': '🐍',
    'Larvitar': '🦎', 'Ditto': '🟣', 'Porygon': '🕹️', 'Scyther': '🗡️',
    'Chansey': '🥚', 'Articuno': '🧊', 'Zapdos': '🌩️', 'Moltres': '☄️',
    'Mewtwo': '🧬', 'Mew': '🩷', 'Lugia': '🌊', 'Ho-Oh': '🌈', 'Celebi': '🍀',
}


def fetch_csv(name):
    req = urllib.request.Request(f"{POKEAPI_CSV}/{name}", headers={"User-Agent": "buddymon-gen"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return list(csv.reader(io.StringIO(r.read().decode())))


def display_name(identifier):
    return SPECIAL_NAME.get(identifier, identifier.replace("-", " ").title())


def main():
    type_name = {row[0]: row[1].title() for row in fetch_csv("types.csv")[1:]}
    primary = {}  # pokemon_id -> type name (slot 1)
    for pid, tid, slot in (r[:3] for r in fetch_csv("pokemon_types.csv")[1:]):
        if slot == "1":
            primary[pid] = type_name.get(tid, "Normal")

    roster, dist = {}, {"common": 0, "uncommon": 0, "rare": 0, "legendary": 0}
    for row in fetch_csv("pokemon_species.csv")[1:]:
        sid = int(row[0])
        if sid > MAX_DEX:
            continue
        name = display_name(row[1])
        if name in STARTER_LINES:
            continue
        catch = int(row[9]) if row[9] else 255
        legendary = row[16] == "1" or row[17] == "1"
        if legendary:
            rarity = "legendary"
        elif catch <= 45:
            rarity = "rare"
        elif catch <= 120:
            rarity = "uncommon"
        else:
            rarity = "common"
        ptype = primary.get(row[0], "Normal")
        emoji = CURATED_EMOJI.get(name) or TYPE_EMOJI.get(ptype, "🐾")
        roster[name] = (ptype, emoji, rarity)
        dist[rarity] += 1

    out = Path(__file__).resolve().parent.parent / "lib" / "dex_roster.py"
    lines = ['"""Generated by tools/gen_dex.py from PokéAPI CSVs (National Dex 1-649).',
             "Do not edit by hand — re-run the generator. name: (type, emoji, rarity).",
             '"""', "", "WILDS = {"]
    lines += [f"    {n!r}: {roster[n]!r}," for n in roster]
    lines.append("}")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"wrote {out}")
    print(f"wilds: {len(roster)}  + 15 starter forms = {len(roster) + 15} total")
    print(f"distribution: {dist}")


if __name__ == "__main__":
    main()
