#!/usr/bin/env python3
"""Generate the evolution table (1-649) from PokéAPI bulk CSVs.

Dev tool, run manually (network):
    python3 tools/gen_evolutions.py

buddymon only levels (no items/trades/friendship), so every evolution trigger
is converted to a level threshold: canonical min_level where the games use one,
sensible stand-ins otherwise (stone 30, trade 32, friendship/move 22). Writes
lib/evolutions.py (committed literal; runtime stays offline). Branches keep
multiple targets — the engine picks among the eligible ones.
"""
import csv
import io
import sys
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from tools.gen_dex import display_name  # noqa: E402

POKEAPI_CSV = "https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv"
MAX_DEX = 649

# trigger_id -> level stand-in when the row has no canonical minimum_level
TRIGGER_DEFAULT = {1: 22, 2: 32, 3: 30, 4: 25}  # level-up(friendship/move)/trade/use-item/shed
FALLBACK_LEVEL = 30


def fetch_csv(name):
    req = urllib.request.Request(f"{POKEAPI_CSV}/{name}", headers={"User-Agent": "buddymon-evo"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return list(csv.reader(io.StringIO(r.read().decode())))


def main():
    species = fetch_csv("pokemon_species.csv")[1:]
    name_of = {int(r[0]): display_name(r[1]) for r in species if int(r[0]) <= MAX_DEX}
    evolves_from = {int(r[0]): (int(r[3]) if r[3] else None) for r in species}

    table = {}  # from_name -> [(to_name, level)]
    for row in fetch_csv("pokemon_evolution.csv")[1:]:
        evolved = int(row[1])
        if evolved > MAX_DEX:
            continue
        src = evolves_from.get(evolved)
        if not src or src > MAX_DEX:
            continue
        trigger = int(row[2]) if row[2] else 1
        min_level = int(row[4]) if row[4] else 0
        level = min_level or TRIGGER_DEFAULT.get(trigger, FALLBACK_LEVEL)
        from_name, to_name = name_of.get(src), name_of.get(evolved)
        if not from_name or not to_name:
            continue
        table.setdefault(from_name, [])
        if to_name not in [t for t, _ in table[from_name]]:
            table[from_name].append((to_name, level))

    for k in table:
        table[k].sort(key=lambda t: (t[1], t[0]))

    out = Path(__file__).resolve().parent.parent / "lib" / "evolutions.py"
    lines = ['"""Generated by tools/gen_evolutions.py from PokéAPI CSVs (Dex 1-649).',
             "from_name -> [(to_name, level), ...]. Non-level triggers (stone/trade/",
             "friendship) are mapped to level stand-ins since buddymon only levels.",
             '"""', "", "EVOLUTIONS = {"]
    for name in sorted(table):
        lines.append(f"    {name!r}: {table[name]!r},")
    lines.append("}")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"wrote {out} — {len(table)} evolving species")
    print("sanity:",
          "Ivysaur", table.get("Ivysaur"),
          "| Charmeleon", table.get("Charmeleon"),
          "| Magikarp", table.get("Magikarp"),
          "| Eevee", len(table.get("Eevee", [])), "branches")


if __name__ == "__main__":
    main()
